Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 28, in <module>
    sg.Column(main_menu_layout,element_justification="center",visible=True,k='-MAINMENUPAGE-')]]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8246, in __init__
    self.Layout(layout)
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8318, in layout
    for row in rows:
               ^^^^
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 28, in <module>
    sg.Column(main_menu_layout,element_justification="center",visible=True,k='-MAINMENUPAGE-')]]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8246, in __init__
    self.Layout(layout)
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8318, in layout
    for row in rows:
               ^^^^
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 28, in <module>
    sg.Column(main_menu_layout,element_justification="center",visible=True,k='-MAINMENUPAGE-')]]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8246, in __init__
    self.Layout(layout)
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8318, in layout
    for row in rows:
               ^^^^
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 28, in <module>
    sg.Column(main_menu_layout,element_justification="center",visible=True,k='-MAINMENUPAGE-')]]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8246, in __init__
    self.Layout(layout)
  File "C:\Users\izzyl\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\PySimpleGUI\PySimpleGUI.py", line 8318, in layout
    for row in rows:
               ^^^^
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
Traceback (most recent call last):
  File "C:\CS361\cryptogenius\cryptogenius-core\main.py", line 6, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
